Themes:
  - Creeper
Metrics: true
Language: en
Debug: false
CmdWhitelist:
    - bb
    - buildbattle
OfflinePlayers: []
ItemBlackList: []
StartCommand:
    Enabled : false
    Command: ''
Rewards:
  Vault:
    Enabled: false
    Winner: 5
    Second: 5
    Third: 5
    Rest: 5
  PlayerPoints:
    Enabled: false
    Winner: 5
    Second: 5
    Third: 5
    Rest: 5
  Command:
    Enabled: false
    Winner: ''
    Second: ''
    Third: ''
    Rest: ''
